name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2.0.0
      
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_KEY }}
          IMAGE_NAME: "manchicken/node-with-awscli"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
